# -*- coding: utf-8 -*-
"""open_pkl_file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_VP7ajmoyhfcmeFu2WHWzSBAWicCTJwy
"""

import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
##########################################################################

data_file_idx = 0
path = r'C:/Users/Atomionics/Desktop/test/'
data = pd.read_pickle(path+'data{}.pkl'.format(data_file_idx))
data = pd.DataFrame(data)
data.columns = ["APD", "CA plus or SRS", "CA minus", "Trigger"]

'''Plot'''
plt.xlim([0, 2e2])
plt.plot(data["CA plus or SRS"])
plt.show()

'''Plot'''
a = plt.plot(data["APD"])
plt.xlim([1.863e5, 1.864e5])
plt.show()

b = plt.plot(data["Trigger"])
plt.xlim([1.863e5, 1.864e5])
plt.show()

c = plt.plot(data["CA plus or SRS"])
plt.xlim([1.863e5, 1.864e5])
plt.show()

plt.plot(data["Trigger"])
plt.xlim([5e4+1e6, 2.5e5+1e6])
plt.show()

